---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
file <- "activity.zip"
download.file(url, file)
unzip(file)
act <- read.csv("activity.csv", header=TRUE)
sumact <- with(act, tapply(steps, date, sum, na.rm=TRUE))
dfsumact <- data.frame(dates=names(sumact), total=sumact)


## What is mean total number of steps taken per day?
hist(dfsumact$total, main="Histogram of Days", xlab="number of steps", ylab="days", col="blue")
mean(dfsumact$total)
median(dfsumact$total)


## What is the average daily activity pattern?
avact <- with(act, tapply(steps, as.factor(interval), mean, na.rm=TRUE))
dfavact <- data.frame(interval=names(avact), total=avact)
library(ggplot2)
graph <- ggplot(data=dfavact, aes(x=interval, y=total, group=1))
graph + geom_line(colour="blue") + labs(x="Interval", y="Average Steps", title="Average Steps per Interval")

# The maximun average steps per interval is at 8:35


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
